name: Github Pages
on:
  schedule:
    - cron: '0 23 * * *'    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
	uses: actions/checkout@v2
      - name: Build
	run: npm i -g notablog && notablog generate .
      - name: Deploy
	uses: JamesIves/github-pages-deploy-action@v4.2.5
	with:
	  token: ${{ secrets.ACCESS_TOKEN }}
     	  repository-name: jht108/jht108.github.io 
     	  BRANCH: main              
     	  FOLDER: public
