name: Github Pages
on:
  schedule:
    - cron: '0 23 * * *'    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
	 # 拉取代码
      - name: Checkout
	uses: actions/checkout@v2
	  # 1、生成静态文件
      - name: Build
	run: npm i -g notablog && notablog generate .
	  # 2、部署到 GitHub Pages
      - name: Deploy
	uses: JamesIves/github-pages-deploy-action@v4.2.5
	with:
	  token: ${{ secrets.ACCESS_TOKEN }}
     	  repository-name: jht108/jht108.github.io # 修改这里
     	  BRANCH: main  # 如果你的仓库默认分支是 master 记得修改这里                    
     	  FOLDER: public
